#!/usr/bin/env bash
# Hook: stack:delete:before
# Removes all Bitwarden entries for the stack
set -euo pipefail

stack="${1}"

[[ -n "${SWRMGR_BW_ORG_ID:-}" ]] || exit 0

echo "Removing Bitwarden credentials for ${stack}..."
swrmgr bitwarden delete "${stack}" || true
