CREATE DATABASE IF NOT EXISTS SWRMGR_metrics;

USE SWRMGR_metrics;

CREATE TABLE IF NOT EXISTS stack_tests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  host VARCHAR(255) NOT NULL,
  stack VARCHAR(255) NOT NULL,
  test_name VARCHAR(255) NOT NULL,
  result ENUM('pass', 'fail') NOT NULL,
  details TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS system_tests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  host VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  result ENUM('pass', 'fail') NOT NULL,
  details TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
